//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4959
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARS.SrvAdres {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stcline.ru", ConfigurationName="SrvAdres.IAdres")]
    public interface IAdres {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stcline.ru/IAdres/GetAdresString", ReplyAction="http://www.stcline.ru/IAdres/GetAdresStringResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(STCLINE.KP50.Bars.Interfaces.Counter))]
        STCLINE.KP50.Bars.Interfaces.AdresResult GetAdresString(STCLINE.KP50.Bars.Interfaces.AdresID adresID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stcline.ru/IAdres/ValidNumID", ReplyAction="http://www.stcline.ru/IAdres/ValidNumIDResponse")]
        STCLINE.KP50.Bars.Interfaces.AdresResult ValidNumID(string numID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAdresChannel : BARS.SrvAdres.IAdres, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AdresClient : System.ServiceModel.ClientBase<BARS.SrvAdres.IAdres>, BARS.SrvAdres.IAdres {
        
        public AdresClient() {
        }
        
        public AdresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public STCLINE.KP50.Bars.Interfaces.AdresResult GetAdresString(STCLINE.KP50.Bars.Interfaces.AdresID adresID) {
            return base.Channel.GetAdresString(adresID);
        }
        
        public STCLINE.KP50.Bars.Interfaces.AdresResult ValidNumID(string numID) {
            return base.Channel.ValidNumID(numID);
        }
    }
}
