//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webroles.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webroles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип действия.
        /// </summary>
        internal static string actions_showTable_actions_type_id {
            get {
                return ResourceManager.GetString("actions_showTable_actions_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая страница.
        /// </summary>
        internal static string actions_showTable_cur_page {
            get {
                return ResourceManager.GetString("actions_showTable_cur_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string actions_showTable_id {
            get {
                return ResourceManager.GetString("actions_showTable_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string actions_showTable_nzp_act {
            get {
                return ResourceManager.GetString("actions_showTable_nzp_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменен пользователем.
        /// </summary>
        internal static string changed_by {
            get {
                return ResourceManager.GetString("changed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время изменения.
        /// </summary>
        internal static string changed_on {
            get {
                return ResourceManager.GetString("changed_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан пользователем ID.
        /// </summary>
        internal static string created_by {
            get {
                return ResourceManager.GetString("created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания.
        /// </summary>
        internal static string created_on {
            get {
                return ResourceManager.GetString("created_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В разработке.
        /// </summary>
        internal static string is_dev {
            get {
                return ResourceManager.GetString("is_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия со страниц.
        /// </summary>
        internal static string nodeText_actions_show {
            get {
                return ResourceManager.GetString("nodeText_actions_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переходы м/у страницами.
        /// </summary>
        internal static string nodeText_page_links {
            get {
                return ResourceManager.GetString("nodeText_page_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string nodeText_s_actionsTable {
            get {
                return ResourceManager.GetString("nodeText_s_actionsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        internal static string nodeText_s_rolesTable {
            get {
                return ResourceManager.GetString("nodeText_s_rolesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы страниц.
        /// </summary>
        internal static string nodeTextPageGroupsTable {
            get {
                return ResourceManager.GetString("nodeTextPageGroupsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страницы.
        /// </summary>
        internal static string nodeTextPagesTable {
            get {
                return ResourceManager.GetString("nodeTextPagesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        internal static string nodeTextProfilesTable {
            get {
                return ResourceManager.GetString("nodeTextProfilesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string nodeTextUsersTable {
            get {
                return ResourceManager.GetString("nodeTextUsersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string page_groupsTable_group_id {
            get {
                return ResourceManager.GetString("page_groupsTable_group_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string page_groupsTable_group_name {
            get {
                return ResourceManager.GetString("page_groupsTable_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С группы.
        /// </summary>
        internal static string page_linksTable_group_from {
            get {
                return ResourceManager.GetString("page_linksTable_group_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На группу.
        /// </summary>
        internal static string page_linksTable_group_to {
            get {
                return ResourceManager.GetString("page_linksTable_group_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Со страницы.
        /// </summary>
        internal static string page_linksTable_page_from {
            get {
                return ResourceManager.GetString("page_linksTable_page_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На страницу.
        /// </summary>
        internal static string page_linksTable_page_to {
            get {
                return ResourceManager.GetString("page_linksTable_page_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url страницы.
        /// </summary>
        internal static string page_url {
            get {
                return ResourceManager.GetString("page_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        internal static string pagesTable_group_id {
            get {
                return ResourceManager.GetString("pagesTable_group_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string pagesTable_hlp {
            get {
                return ResourceManager.GetString("pagesTable_hlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string pagesTable_nzp_page {
            get {
                return ResourceManager.GetString("pagesTable_nzp_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое наименование.
        /// </summary>
        internal static string pagesTable_page_menu {
            get {
                return ResourceManager.GetString("pagesTable_page_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string pagesTable_page_name {
            get {
                return ResourceManager.GetString("pagesTable_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип страницы.
        /// </summary>
        internal static string pagesTable_page_type {
            get {
                return ResourceManager.GetString("pagesTable_page_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пункт меню.
        /// </summary>
        internal static string pagesTable_up_kod {
            get {
                return ResourceManager.GetString("pagesTable_up_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование базы данных.
        /// </summary>
        internal static string profilesTable_db {
            get {
                return ResourceManager.GetString("profilesTable_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string profilesTable_id {
            get {
                return ResourceManager.GetString("profilesTable_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string profilesTable_name {
            get {
                return ResourceManager.GetString("profilesTable_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string profilesTable_profiles_name {
            get {
                return ResourceManager.GetString("profilesTable_profiles_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string s_actionsTable_act_hlp {
            get {
                return ResourceManager.GetString("s_actionsTable_act_hlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string s_actionsTable_act_name {
            get {
                return ResourceManager.GetString("s_actionsTable_act_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string s_actionsTable_nzp_act {
            get {
                return ResourceManager.GetString("s_actionsTable_nzp_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсистема.
        /// </summary>
        internal static string s_rolesTable_is_subsystem {
            get {
                return ResourceManager.GetString("s_rolesTable_is_subsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string s_rolesTable_nzp_role {
            get {
                return ResourceManager.GetString("s_rolesTable_nzp_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        internal static string s_rolesTable_role {
            get {
                return ResourceManager.GetString("s_rolesTable_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядковый номер.
        /// </summary>
        internal static string s_rolesTable_sort {
            get {
                return ResourceManager.GetString("s_rolesTable_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядковый номер.
        /// </summary>
        internal static string sort_kod {
            get {
                return ResourceManager.GetString("sort_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменен пользователем Имя.
        /// </summary>
        internal static string user_name_chang {
            get {
                return ResourceManager.GetString("user_name_chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан пользователем Имя.
        /// </summary>
        internal static string user_name_creat {
            get {
                return ResourceManager.GetString("user_name_creat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string usersTable_id {
            get {
                return ResourceManager.GetString("usersTable_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокирован.
        /// </summary>
        internal static string usersTable_is_blocked {
            get {
                return ResourceManager.GetString("usersTable_is_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string usersTable_login {
            get {
                return ResourceManager.GetString("usersTable_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string usersTable_user_name {
            get {
                return ResourceManager.GetString("usersTable_user_name", resourceCulture);
            }
        }
    }
}
