//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4952
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARS.SrvAbout {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stcline.ru", ConfigurationName="SrvAbout.IAboutCompany")]
    public interface IAboutCompany {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stcline.ru/IAboutCompany/GetAboutCompany", ReplyAction="http://www.stcline.ru/IAboutCompany/GetAboutCompanyResponse")]
        STCLINE.KP50.Bars.Services.AboutResult GetAboutCompany();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAboutCompanyChannel : BARS.SrvAbout.IAboutCompany, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AboutCompanyClient : System.ServiceModel.ClientBase<BARS.SrvAbout.IAboutCompany>, BARS.SrvAbout.IAboutCompany {
        
        public AboutCompanyClient() {
        }
        
        public AboutCompanyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AboutCompanyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AboutCompanyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AboutCompanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public STCLINE.KP50.Bars.Services.AboutResult GetAboutCompany() {
            return base.Channel.GetAboutCompany();
        }
    }
}
