 drop table if exists t;  
 select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  
 into temp t from ntul01_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   

 drop table if exists t2;  
 select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  
 into temp t2 from ntul01_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv 
 and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s 
 and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  

 alter table t2 add isdel integer; 
 create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  
 update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    
 tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s 
 and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, 
 coalesce(num_ls,0) desc limit 1);  update ntul01_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);
 
----------------------------
 drop table if exists t;  
 select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul08_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   
 
 drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  
 into temp t2 from ntul08_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   
 and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  
 
 alter table t2 add isdel integer; 
 create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  
 
 update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    
 tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s 
 and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  
 
 update ntul08_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  
 select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  
 into temp t from ntul06_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   

 drop table if exists t2;  
 select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  
 into temp t2 from ntul06_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   
 and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  

 alter table t2 add isdel integer; 
 create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  
 
 update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    
 tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   
 order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  

 update ntul06_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  

 select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul09_data.tarif where is_actual=1   
 group by 1,2,3,4,5,6,7 having count(*) > 1;   

 drop table if exists t2;  
 select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  
 into temp t2 from ntul09_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   
 and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;
  
 alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  

 update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar 
 and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s 
 and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  

 update ntul09_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul05_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul05_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul05_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul03_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul03_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul03_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul07_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul07_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul07_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul11_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul11_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul11_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul12_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul12_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul12_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul14_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul14_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul14_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul13_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul13_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul13_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul16_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul16_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul16_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul17_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul17_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul17_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul19_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul19_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul19_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul20_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul20_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul20_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul21_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul21_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul21_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul18_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul18_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul18_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul10_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul10_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul10_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul22_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul22_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul22_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul02_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul02_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul02_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from efrem_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from efrem_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update efrem_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul24_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul24_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul24_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from belev_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from belev_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update belev_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from tula1_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from tula1_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update tula1_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from tula_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from tula_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update tula_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul23_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul23_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul23_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from alex_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from alex_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update alex_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul25_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul25_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul25_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);

----------------------------
 drop table if exists t;  select nzp_serv,nzp_supp,nzp_frm,tarif,dat_s,dat_po,nzp_kvar  into temp t from ntul04_data.tarif where is_actual=1   group by 1,2,3,4,5,6,7 having count(*) > 1;   drop table if exists t2;  select nzp_tarif, num_ls,tf.nzp_serv,tf.nzp_supp,tf.nzp_frm,tf.tarif,tf.dat_s,tf.dat_po,tf.nzp_kvar,tf.is_actual  into temp t2 from ntul04_data.tarif tf, t where tf.nzp_supp = t.nzp_supp and tf.nzp_serv = t.nzp_serv and tf.nzp_frm = t.nzp_frm and tf.is_actual=1   and tf.nzp_kvar = t.nzp_kvar  and tf.dat_s = t.dat_s and tf.dat_po = t.dat_po and t.tarif = tf.tarif;  alter table t2 add isdel integer; create index i1 on t2 (nzp_kvar, nzp_supp, nzp_serv, nzp_frm, dat_s, dat_po, tarif);  update t2 set isdel = 1 where t2.nzp_tarif in (select nzp_tarif from t2 tt where tt.nzp_kvar = t2.nzp_kvar and    tt.nzp_supp =  t2.nzp_supp and tt.nzp_serv =  t2.nzp_serv and tt.nzp_frm =  t2.nzp_frm and tt.dat_s =  t2.dat_s and tt.dat_po =  t2.dat_po and tt.tarif =  t2.tarif   order by nzp_kvar, nzp_serv, nzp_supp, dat_s, dat_po, tarif, coalesce(num_ls,0) desc limit 1);  update ntul04_data.tarif set is_actual = 100 where nzp_tarif in (select nzp_tarif from t2 where isdel is null);
