//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.4959
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BARS.SrvCounter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stcline.ru", ConfigurationName="SrvCounter.ICounter")]
    public interface ICounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stcline.ru/ICounter/GetCounters", ReplyAction="http://www.stcline.ru/ICounter/GetCountersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(STCLINE.KP50.Bars.Interfaces.Counter))]
        STCLINE.KP50.Bars.Interfaces.CounterResult GetCounters(STCLINE.KP50.Bars.Interfaces.AdresID adresID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICounterChannel : BARS.SrvCounter.ICounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CounterClient : System.ServiceModel.ClientBase<BARS.SrvCounter.ICounter>, BARS.SrvCounter.ICounter {
        
        public CounterClient() {
        }
        
        public CounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public STCLINE.KP50.Bars.Interfaces.CounterResult GetCounters(STCLINE.KP50.Bars.Interfaces.AdresID adresID) {
            return base.Channel.GetCounters(adresID);
        }
    }
}
