//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///  if !cnt!==1 (
        ///  SET schema=%~1
        ///  ) else if !cnt!==2 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==3 (
        ///  SET work_dir=%~1
        ///  ) else if !cnt!==4 (
        ///  SET host=%~1
        ///  ) else if !cnt!==5 (
        ///  SET port=%~1
        ///  ) else if !cnt!==6 (
        ///  SET db=%~1
        ///  ) else if !cnt!==7 (
        ///  SET user_name=%~1
        ///  ) else if !cnt!==8 (
        ///  SET PGPASSWORD=%~1
        ///  ) else if !cnt!==9 (
        ///  SET nzp=%~1
        ///  )
        ///
        ///  shift
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gkh_del {
            get {
                return ResourceManager.GetString("gkh_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///  if !cnt!==1 (
        ///  SET schema=%~1
        ///  ) else if !cnt!==2 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==3 (
        ///  SET work_dir=%~1
        ///  ) else if !cnt!==4 (
        ///  SET host=%~1
        ///  ) else if !cnt!==5 (
        ///  SET port=%~1
        ///  ) else if !cnt!==6 (
        ///  SET db=%~1
        ///  ) else if !cnt!==7 (
        ///  SET user_name=%~1
        ///  ) else if !cnt!==8 (
        ///  SET PGPASSWORD=%~1
        ///  ) else if !cnt!==9 (
        ///  SET nzp=%~1
        ///  ) else if !cnt! [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gkh_must_calc {
            get {
                return ResourceManager.GetString("gkh_must_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///
        ///SET par=nzp_pack_ls
        ///           
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///  if !cnt!==1 (
        ///  SET schema=%~1
        ///  ) else if !cnt!==2 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==3 (
        ///  SET work_dir=%~1
        ///  ) else if !cnt!==4 (
        ///  SET host=%~1
        ///  ) else if !cnt!==5 (
        ///  SET port=%~1
        ///  ) else if !cnt!==6 (
        ///  SET db=%~1
        ///  ) else if !cnt!==7 (
        ///  SET user_name=%~1
        ///  ) else if !cnt!==8 (
        ///  SET PGPASSWORD=%~1
        ///  ) else if !cnt!==9 ( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gkh_pack_ls {
            get {
                return ResourceManager.GetString("gkh_pack_ls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///                  
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///echo parapaparam
        ///
        ///  if !cnt!==1 (
        ///  SET schema=%~1
        ///  ) else if !cnt!==2 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==3 (
        ///  SET host=%~1
        ///  ) else if !cnt!==4 (
        ///  SET port=%~1
        ///  ) else if !cnt!==5 (
        ///  SET db=%~1
        ///  ) else if !cnt!==6 (
        ///  SET user_name=%~1
        ///  ) else if !cnt!==7 (
        ///  SET PGPASSWORD=%~1
        ///  )
        ///
        ///  shift
        ///  set /a cnt=!cnt!+1
        ///
        ///  if not &quot;%~1&quot;==&quot;&quot; got [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gkh_triggers_data_off {
            get {
                return ResourceManager.GetString("gkh_triggers_data_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///  if !cnt!==1 (
        ///  SET schema=%~1
        ///  ) else if !cnt!==2 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==3 (
        ///  SET host=%~1
        ///  ) else if !cnt!==4 (
        ///  SET port=%~1
        ///  ) else if !cnt!==5 (
        ///  SET db=%~1
        ///  ) else if !cnt!==6 (
        ///  SET user_name=%~1
        ///  ) else if !cnt!==7 (
        ///  SET PGPASSWORD=%~1
        ///  )
        ///
        ///  shift
        ///  set /a cnt=!cnt!+1
        ///
        ///  if not &quot;%~1&quot;==&quot;&quot; goto :parameters
        ///
        ///goto :EOF
        ///
        ///:body
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gkh_triggers_data_on {
            get {
                return ResourceManager.GetString("gkh_triggers_data_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///  if !cnt!==1 (
        ///  SET schema=%~1
        ///  ) else if !cnt!==2 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==3 (
        ///  SET work_dir=%~1
        ///  ) else if !cnt!==4 (
        ///  SET host=%~1
        ///  ) else if !cnt!==5 (
        ///  SET port=%~1
        ///  ) else if !cnt!==6 (
        ///  SET db=%~1
        ///  ) else if !cnt!==7 (
        ///  SET user_name=%~1
        ///  ) else if !cnt!==8 (
        ///  SET PGPASSWORD=%~1
        ///  ) else if !cnt!==9 (
        ///  SET nzp=%~1
        ///  ) else if !cnt! [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gkh_upd {
            get {
                return ResourceManager.GetString("gkh_upd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ISOto1251 {
            get {
                object obj = ResourceManager.GetObject("ISOto1251", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///setlocal ENABLEDELAYEDEXPANSION
        ///
        ///chcp 1251&gt;nul
        ///
        ///SET cnt=1
        ///
        ///call :parameters %*
        ///goto :body
        ///
        ///:parameters
        ///
        ///  if !cnt!==1 (
        ///  SET kod_uk=%~1
        ///  ) else if !cnt!==2 (
        ///  SET dat_calc=%~1
        ///  ) else if !cnt!==3 (
        ///  SET pg_dir=%~1
        ///  ) else if !cnt!==4 (
        ///  SET work_dir=%~1
        ///  ) else if !cnt!==5 (
        ///  SET host=%~1
        ///  ) else if !cnt!==6 (
        ///  SET port=%~1
        ///  ) else if !cnt!==7 (
        ///  SET db=%~1
        ///  ) else if !cnt!==8 (
        ///  SET PGPASSWORD=%~1
        ///  ) else if !cnt!==9 (
        ///  SET nzp_load=%~1
        ///  ) else if [rest of string was truncated]&quot;;.
        /// </summary>
        public static string part_payment {
            get {
                return ResourceManager.GetString("part_payment", resourceCulture);
            }
        }
    }
}
