//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договору.
        /// </summary>
        internal static string ContractNameDP {
            get {
                return ResourceManager.GetString("ContractNameDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор(ы).
        /// </summary>
        internal static string ContractNameEChMChIP {
            get {
                return ResourceManager.GetString("ContractNameEChMChIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договора(ов).
        /// </summary>
        internal static string ContractNameEChMChRP {
            get {
                return ResourceManager.GetString("ContractNameEChMChRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор(ы).
        /// </summary>
        internal static string ContractNameEChMChVP {
            get {
                return ResourceManager.GetString("ContractNameEChMChVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор.
        /// </summary>
        internal static string ContractNameIP {
            get {
                return ResourceManager.GetString("ContractNameIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дого&lt;wbr&gt;вор.
        /// </summary>
        internal static string ContractNameIPWbr {
            get {
                return ResourceManager.GetString("ContractNameIPWbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договоры.
        /// </summary>
        internal static string ContractNameMCh {
            get {
                return ResourceManager.GetString("ContractNameMCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договорам.
        /// </summary>
        internal static string ContractNameMChDP {
            get {
                return ResourceManager.GetString("ContractNameMChDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договоров.
        /// </summary>
        internal static string ContractNameMChRP {
            get {
                return ResourceManager.GetString("ContractNameMChRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договоре.
        /// </summary>
        internal static string ContractNamePP {
            get {
                return ResourceManager.GetString("ContractNamePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договора.
        /// </summary>
        internal static string ContractNameRP {
            get {
                return ResourceManager.GetString("ContractNameRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договором.
        /// </summary>
        internal static string ContractNameTP {
            get {
                return ResourceManager.GetString("ContractNameTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор.
        /// </summary>
        internal static string ContractNameVP {
            get {
                return ResourceManager.GetString("ContractNameVP", resourceCulture);
            }
        }
    }
}
